# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

$script = <<-SCRIPT
apt-get update
apt-get install -y net-tools vim ansible tree
echo "192.168.121.146 automation" >> /etc/hosts
# echo "neofetch" >> /home/vagrant/.bashrc 
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "automation" do |automation|
    automation.vm.box = "generic/ubuntu2004"
    automation.vm.network "private_network", ip: "192.168.121.146"
    automation.vm.synced_folder ".", "/vagrant", disabled: false
    automation.vm.hostname = "automation"
  end

  config.vm.provision "shell", inline: $script

  # copy git.yml to vagrant folder
  config.vm.provision "file", source: "git.yml", destination: "/home/vagrant/git.yml"
  
  # run ansible playbook on VM as vagrant user
  config.vm.provision "shell", inline: "ansible-playbook git.yml -v", privileged: false

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider "libvirt" do |lb|
    lb.memory = "2048"
    lb.cpus = "2"
  end
end
