# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

$script = <<-SCRIPT
apt update
apt install -y net-tools vim tree ncdu file jq curl zip wget

# Install terminal c3270
apt install -y c3270

# Install mainframe hercules mvs3.8 on vagrant folder
wget https://wotho.pebble-beach.ch/tk4-/tk4-_v1.00_current.zip --no-check-certificate
unzip tk4-_v1.00_current.zip -d /home/vagrant/mvs38
rm -vf /home/vagrant/tk4-_v1.00_current.zip
chown -R vagrant:vagrant /home/vagrant

echo "192.168.121.146 mainframe" >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "mainframe" do |hercules|
    hercules.vm.box = "generic/ubuntu2004"
    hercules.vm.network "private_network", ip: "192.168.121.146"
    hercules.vm.synced_folder ".", "/vagrant", disabled: false
    hercules.vm.hostname = "mainframe"
  end

  config.vm.provision "shell", inline: $script

  # copy hercules_mainframe.sh to vagrant folder
  config.vm.provision "file", source: "hercules_mainframe.sh", destination: "/home/vagrant/hercules_mainframe.sh"
  
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider "libvirt" do |lb|
    lb.memory = "2048"
    lb.cpus = "2"
  end
end

