# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

$script = <<-SCRIPT
yum install epel-release -y
yum install -y net-tools vim tree git ansible jq
echo "192.168.121.146 minikube" >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "minikube" do |docker|
    docker.vm.box = "generic/centos7"
    docker.vm.hostname = "minikube"
    docker.vm.network "private_network", ip: "192.168.121.146"
    docker.vm.network "forwarded_port", guest: 8080, host: 8080
    docker.vm.network "forwarded_port", guest: 8443, host: 8443
    docker.vm.synced_folder ".", "/vagrant", disabled: false
  end

  # boostrap script
  config.vm.provision "shell", inline: $script

  # copy git.yml to vagrant folder
  config.vm.provision "file", source: "git.yml", destination: "/home/vagrant/git.yml"
  
  # run ansible playbook on VM as vagrant user
  config.vm.provision "shell", inline: "ansible-playbook git.yml", privileged: false
  
  # config.vm.provision "shell" do |git|
  #   git.inline = "ansible-playbook git.yml"
  #   git.privileged = false
  # end   
 
  # Install Docker CE via ansible
  config.vm.provision "shell", inline: "ansible-playbook ansible_automation/docker-ce/docker-ce.yml", privileged: false
 
  # Install minikube + kubectl
  config.vm.provision "shell", path: "install_minikube_kubectl.sh"

  # Install helm on
  config.vm.provision "shell", path: "install_helm.sh", privileged: false

  # trigger reload plugin --> "power off/on VM"
  config.vm.provision "reload"
  
  # Initiate minikube ...
  config.vm.provision "shell", path: "initiate_minikube.sh", privileged: false

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider "libvirt" do |lb|
    lb.memory = "8765"
    lb.cpus = "4"
  end
end
