# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

$script = <<-SCRIPT
pkg update
pkg install -y git htop neofetch bash-completion kubectl helm

# Autocompletion
echo "[[ -f /usr/local/share/bash-completion/bash_completion.sh ]] && source /usr/local/share/bash-completion/bash_completion.sh" >> /home/vagrant/.profile
echo "source <(kubectl completion bash)"  >> /home/vagrant/.profile
echo "source <(helm completion bash)"  >> /home/vagrant/.profile

echo "192.168.39.146 automation" >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  # config.vm.box = "generic/freebsd13"

  config.vm.define "automation" do |automation|
    automation.vm.box = "generic/freebsd13"
    automation.vm.network "private_network", ip: "192.168.39.146"
    automation.vm.synced_folder ".", "/vagrant", disabled: false
    automation.vm.hostname = "automation"
  end

  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.hostname = "freebsd13"

  # bootstrap
  config.vm.provision "shell", inline: $script

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider "libvirt" do |lb|
    lb.memory = "2048"
  end
end
