---
- name: playbooks
  hosts: localhost
  become: false
  gather_facts: true
  tasks:
    - name: Clone my own repo 
      git:
        repo: "https://github.com/dcmikki/ansible_automation"
        dest: "{{ lookup('env', 'HOME') }}/ansible_automation"
        version: main
